version: '3.8'

services:
  postgres1:
    build: .
    container_name: postgres1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork
    ports:
      - "5433:5432"

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge